# -*- coding: utf-8 -*-
"""ml2_NB_thinh

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lGHEcXEgw6bqpa8vhqF3uvqfgavCAWBy
"""

# Nhớ cài thư viện rồi mới chạy nghe
!pip install underthesea scikit-learn joblib
keywords= {
    "giáo dục": [
        "nữ sinh", "nam sinh", "thầy giáo", "cô giáo", "giảng viên", "học đường", "học sinh",
        "điểm thi", "gian lận", "trường học", "phụ huynh", "kỷ luật", "đình chỉ", "bằng cấp", "học phí", "đề thi", "nhà trường"
    ],
    "công nghệ": [
        "AI", "trí tuệ nhân tạo", "chatgpt", "phần mềm", "tiền số", "crypto",
        "hacker", "dữ liệu", "tấn công mạng", "deepfake", "thuật toán",
        "nền tảng", "robot", "thiết bị"
    ],
    "giải trí": [
        "nghệ sĩ", "ca sĩ", "hoa hậu", "showbiz", "livestream", "Scandal", "clip nóng",
        "tình ái", "ngoại tình", "đấu tố", "sao kê", "từ thiện", "fan", "anti-fan",
        "hợp đồng âm nhạc", "showbiz", "hậu trường", "chia tay", "tiktok"
    ],
    "kinh doanh": [
        "trái phiếu", "cổ phiếu", "lừa đảo", "tài sản", "giám đốc", "hợp đồng", "bất động sản", "chiếm đoạt",
        "phá sản", "nợ nần", "đa cấp", "đầu tư", "lợi nhuận", "vỡ nợ", "tài chính"
    ]
}

!pip install underthesea



import json
import joblib
from underthesea import word_tokenize
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import MultiLabelBinarizer
from sklearn.multiclass import OneVsRestClassifier
from sklearn.model_selection import train_test_split

# Nạp dữ liệu
file_path = '/content/data.json'
with open(file_path, 'r', encoding='utf-8') as f:
    data = json.load(f)

X=[]
y=[]

for item in data.values():
    X.append(item['title'])
    tags = [t.strip().lower() for t in item['tag'].split(',')]
    y.append(tags)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# TIẾN HÀNH MLB VÀ PREPROCESS TRÊN DỮ LIỆU TỔNG
mlb = MultiLabelBinarizer()
y_train = mlb.fit_transform(y_train)
categories = mlb.classes_

STOPWORDS = [
    "vụ", "bị", "về", "của", "và", "là", "các", "những", "một", "có", "đã", "đang", "được", "với", "cho", "ra", "vào",
    "lộ", "nóng", "nhạy_cảm", "sốc", "xôn_xao", "scandal", "drama", "cực_căng", "hot",
    "đấu_tố", "bóc_phốt", "lên_tiếng", "ồn_ào", "lùm_xùm", "nghi_vấn",
    "tranh_cãi", "bất_ngờ", "mới_nhất", "hiện_nay", "hé_lộ", "sự_thật"
]
def preprocess_drama(text):
    tokens_raw = word_tokenize(text.lower(), format="text")
    tokens = tokens_raw.split()
    cleaned_text = " ".join([t for t in tokens if t not in STOPWORDS])
    return cleaned_text
# Sử dụng hàm preprocess của bạn trên X_train_final
X_train_preprocessed = [preprocess_drama(t) for t in X_train]

# HUẤN LUYỆN
model = make_pipeline(TfidfVectorizer(ngram_range=(1, 2),min_df=1,max_df=0.8),OneVsRestClassifier(MultinomialNB(alpha=0.1)))
model.fit(X_train_preprocessed, y_train)

# Lưu mô hình
joblib.dump((model, mlb), '/content/model_phanloai_drama_nb.pkl')
print(f"HL thành công với {len(X_train)} mẫu dữ liệu!")



import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import (
    accuracy_score, f1_score, hamming_loss,
    roc_curve, auc, classification_report
)
import joblib

model, mlb = joblib.load('/content/model_phanloai_drama_nb.pkl')

X_test_preprocessed = [preprocess_drama(t) for t in X_test]
y_pred_proba        = model.predict_proba(X_test_preprocessed)
y_test_binarized    = mlb.transform(y_test)
categories          = mlb.classes_

# ── 1. TÌM THRESHOLD TỐI ƯU theo F1-macro ─────────────────────────────────
# Threshold tối ưu từ ROC (Youden's J)
per_label_threshold = {
    'công nghệ' : 0.76,
    'giáo dục'  : 0.30,
    'giải trí'  : 0.19,
    'kinh doanh': 0.07,
}

thresholds = np.array([per_label_threshold[c] for c in categories])

y_pred_per = (y_pred_proba >= thresholds).astype(int)
for i, row in enumerate(y_pred_per):
    if row.sum() == 0:
        y_pred_per[i][np.argmax(y_pred_proba[i])] = 1

print(f"F1-macro  : {f1_score(y_test_binarized, y_pred_per, average='macro', zero_division=0):.4f}")
print(f"F1-micro  : {f1_score(y_test_binarized, y_pred_per, average='micro', zero_division=0):.4f}")
print(classification_report(y_test_binarized, y_pred_per,
                             target_names=categories, zero_division=0))

best_f1 = -1  # Initialize best_f1 to a very small number
best_threshold = 0.0 # Initialize best_threshold

for threshold in np.arange(0.05, 0.95, 0.01):
    y_pred_tmp = (y_pred_proba >= threshold).astype(int)
    # Đảm bảo mỗi mẫu có ít nhất 1 nhãn
    for i, row in enumerate(y_pred_tmp):
        if row.sum() == 0:
            y_pred_tmp[i][np.argmax(y_pred_proba[i])] = 1
    f1 = f1_score(y_test_binarized, y_pred_tmp, average='macro', zero_division=0)
    if f1 > best_f1:
        best_f1, best_threshold = f1, threshold

print(f"Threshold tốt nhất : {best_threshold:.2f}")
print(f"F1-macro tốt nhất  : {best_f1:.4f}")

# ── 2. ĐÁNH GIÁ VỚI THRESHOLD TỐI ƯU ──────────────────────────────────────
y_pred_opt = (y_pred_proba >= best_threshold).astype(int)
for i, row in enumerate(y_pred_opt):
    if row.sum() == 0:
        y_pred_opt[i][np.argmax(y_pred_proba[i])] = 1

print(f"\nExact-match Accuracy : {accuracy_score(y_test_binarized, y_pred_opt):.4f}")
print(f"Hamming Loss         : {hamming_loss(y_test_binarized, y_pred_opt):.4f}  (càng thấp càng tốt)")
print(f"F1-macro             : {f1_score(y_test_binarized, y_pred_opt, average='macro', zero_division=0):.4f}")
print(f"F1-micro             : {f1_score(y_test_binarized, y_pred_opt, average='micro', zero_division=0):.4f}")
print("\n── Báo cáo chi tiết theo nhãn ──")
print(classification_report(y_test_binarized, y_pred_opt,
                             target_names=categories, zero_division=0))

# ── 3. VẼ ROC CURVE CHO TỪNG NHÃN ─────────────────────────────────────────
fig, axes = plt.subplots(2, 2, figsize=(12, 10))
axes = axes.flatten()
colors = ['#e74c3c', '#3498db', '#2ecc71', '#f39c12']

roc_data = {}  # lưu lại để phân tích

for i, (cat, color) in enumerate(zip(categories, colors)):
    fpr, tpr, thresholds = roc_curve(y_test_binarized[:, i], y_pred_proba[:, i])
    roc_auc = auc(fpr, tpr)
    roc_data[cat] = {'fpr': fpr, 'tpr': tpr, 'thresholds': thresholds, 'auc': roc_auc}

    # Tìm điểm tối ưu trên ROC (Youden's J = TPR - FPR lớn nhất)
    optimal_idx = np.argmax(tpr - fpr)
    optimal_threshold = thresholds[optimal_idx]

    axes[i].plot(fpr, tpr, color=color, lw=2,
                 label=f'AUC = {roc_auc:.3f}')
    axes[i].plot(fpr[optimal_idx], tpr[optimal_idx], 'ko', markersize=8,
                 label=f'Threshold tối ưu = {optimal_threshold:.2f}')
    axes[i].plot([0, 1], [0, 1], 'k--', lw=1, alpha=0.5)
    axes[i].fill_between(fpr, tpr, alpha=0.1, color=color)
    axes[i].set_xlim([0, 1])
    axes[i].set_ylim([0, 1.02])
    axes[i].set_xlabel('False Positive Rate', fontsize=11)
    axes[i].set_ylabel('True Positive Rate', fontsize=11)
    axes[i].set_title(f'ROC — {cat.upper()}', fontsize=13, fontweight='bold')
    axes[i].legend(loc='lower right', fontsize=10)
    axes[i].grid(True, alpha=0.3)

    print(f"\n[{cat}]  AUC = {roc_auc:.3f}  |  Threshold tối ưu (Youden) = {optimal_threshold:.2f}")
    print(f"  → TPR (Recall) = {tpr[optimal_idx]:.3f}  |  FPR = {fpr[optimal_idx]:.3f}")

plt.suptitle('ROC Curve — Phân loại đa nhãn báo chí Việt Nam',
             fontsize=15, fontweight='bold', y=1.01)
plt.tight_layout()
plt.savefig('roc_curves.png', dpi=150, bbox_inches='tight')
plt.show()
print("\nĐã lưu: roc_curves.png")

# ── 4. IN KẾT QUẢ DỰ ĐOÁN CHI TIẾT ───────────────────────────────────────
print("\n── Dự đoán chi tiết (threshold tối ưu) ──\n")
for i in range(len(X_test)):
    true_labels = mlb.inverse_transform(y_test_binarized[i].reshape(1, -1))[0]
    pred_labels = mlb.inverse_transform(y_pred_opt[i].reshape(1, -1))[0]
    status = "✓" if set(true_labels) == set(pred_labels) else \
             "△" if set(pred_labels) & set(true_labels) else "✗"
    print(f"[{status}] {X_test[i]}")
    print(f"    Thật   : {list(true_labels)}")
    print(f"    Dự đoán: {list(pred_labels)}\n") [1 0 1 1] 0 0 0 0 ->1/4